#!/usr/bin/env bash

if [ -z "${CLARA_HOME}" ]; then
    echo "Error: \$CLARA_HOME is not defined."
    exit 1
fi

if [ -z "${CLASSPATH}" ]; then
    CLASSPATH="${CLARA_HOME}/lib/*"
    export CLASSPATH
fi

if [ -n "${JAVA_OPTS}" ]; then
    jvm_options=(${JAVA_OPTS})
else
    jvm_options=(-Xms1024m -Xmx2048m -XX:+UseNUMA -XX:+UseBiasedLocking)
fi

java_wrapper=${CLARA_HOME}/lib/clara/run-java

exec "${java_wrapper}" "${jvm_options[@]}" org.jlab.clara.std.orchestrators.GenericOrchestrator "$@"
