#!/usr/bin/env bash

if [ -z "${CLARA_HOME}" ]; then
    echo "Error: \$CLARA_HOME is not defined."
    exit 1
fi

# find plugins directory
if [ -n "${CLARA_PLUGINS}" ]; then
    if [ ! -d "${CLARA_PLUGINS}" ]; then
        echo "Error: \$CLARA_PLUGINS is not a directory."
        exit 1
    fi
    plugins_dir="${CLARA_PLUGINS}"
else
    plugins_dir="${CLARA_HOME}/plugins"
fi

# set default classpath
if [ -z "${CLASSPATH}" ]; then
    CLASSPATH="${CLARA_HOME}/lib/*"

    # Add every plugin
    for plugin in "${plugins_dir}"/*/; do
        plugin=${plugin%*/}
        if [ "${plugin##*/}" = "clas12" ]; then # COAT has special needs
            CLASSPATH+=":${plugin}/lib/clas/*:${plugin}/lib/services/*"
        else
            CLASSPATH+=":${plugin}/services/*:${plugin}/lib/*"
        fi
    done

    CLASSPATH+=":${CLARA_HOME}/services/*"
    export CLASSPATH
fi

if [ -n "${JAVA_OPTS}" ]; then
    jvm_options=(${JAVA_OPTS})
else
    jvm_options=(-Xms256m)
fi

java_wrapper=${CLARA_HOME}/lib/clara/run-java

exec "${java_wrapper}" "${jvm_options[@]}" org.jlab.clara.std.cli.ClaraShell "$@"
