#!/usr/bin/env bash
# author Vardan Gyurjyan
# date 10.28.16

if ! [ -n "$CLARA_HOME" ]; then
    echo "CLARA_HOME is not defined. Exiting..."
    exit
fi

command_exists () {
    type "$1" &> /dev/null ;
}

if ! command_exists wget ; then
echo "Can not run wget. Exiting..."
exit
fi

if ! command_exists git ; then
echo "Can not run git. Exiting..."
exit
fi

echo #############################################################
echo "Downloading and installing CLARA run-time and CLAS12 plugin"
accessing git repository...

git clone

OS="`uname`"
case $OS in
  'Linux')
if $(uname -a | grep 'x86_64'); then
  cd $CLARA_HOME/jre/linux-64
  wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F" "http://download.oracle.com/otn-pub/java/jdk/8u112-b15/jre-8u112-linux-x64.tar.gz"
  tar xvzf jre-8u112-linux-x64.tar.gz
else
  cd $CLARA_HOME/jre/linux-i586
  wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F" "http://download.oracle.com/otn-pub/java/jdk/8u112-b15/jre-8u112-linux-i586.tar.gz"
  tar xvzf jre-8u112-linux-i586.tar.gz
fi
    ;;
  'WindowsNT')
    OS='Windows'
    ;;
  'Darwin')
  cd $CLARA_HOME/jre/macosx-64
  wget --no-cookies --no-check-certificate --header "Cookie: gpw_e24=http%3A%2F%2Fwww.oracle.com%2F" "http://download.oracle.com/otn-pub/java/jdk/8u112-b16/jre-8u112-macosx-x64.tar.gz"
  tar xvzf jre-8u112-macosx-x64.tar.gz
    ;;
  *) ;;
esac


