#!/usr/bin/env bash
# author Vardan Gyurjyan
# date 10.28.16

if ! [ -n "$CLARA_HOME" ]; then
    echo "CLARA_HOME is not defined. Exiting..."
    exit
fi

    case "$1" in
      -u | --update)
	  rm -rf $CLARA_HOME
	  ;;
	esac

command_exists () {
    type "$1" &> /dev/null ;
}

if ! command_exists git ; then
echo "Can not run git. Exiting..."
exit
fi

echo "Creating clara working directory ..."
mkdir clara-work
cd clara-work

echo "Downloading and building xMsg package ..."
git clone --depth 1 https://github.com/JeffersonLab/xmsg-java.git
cd xmsg-java
./gradlew install

cd ..
echo "Downloading and building clara-java package ..."
git clone --depth 1 https://github.com/JeffersonLab/clara-java.git
cd clara-java
./gradlew install
./gradlew deploy


cd ..
echo "Downloading coat-java and jre packages ..."
mkdir $CLARA_HOME/jre

OS="`uname`"
case $OS in
  'Linux')
  if $(uname -a | grep 'x86_64'); then
    wget https://userweb.jlab.org/~gurjyan/clara-cre/linux-64.tar.gz
    mv linux-64.tar.gz $CLARA_HOME/jre
  else
     wget https://userweb.jlab.org/~gurjyan/clara-cre/linux-i586.tar.gz
    mv linux-i586.tar.gz $CLARA_HOME/jre
  fi
    ;;
#  'WindowsNT')
#    OS='Windows'
#    ;;
  'Darwin')
 curl "https://userweb.jlab.org/~gurjyan/clara-cre/macosx-64.tar.gz" -o macosx-64.tar.gz
    mv macosx-64.tar.gz $CLARA_HOME/jre
    ;;
  *) ;;
esac

mkdir $CLARA_HOME/plugins

echo "Installing jre ..."
cd $CLARA_HOME/jre
tar xvzf *.tar.*

echo done