#!/usr/bin/env bash
# author Vardan Gyurjyan
# date 10.28.16

command_exists () {
    type "$1" &> /dev/null ;
}

if ! [ -n "$CLARA_HOME" ]; then
    echo "CLARA_HOME is not defined. Exiting..."
    exit
fi
if ! [ -n "$JAVA_HOME" ]; then
    echo "CLARA_HOME is not defined. Exiting..."
    exit
fi

if ! command_exists git ; then
echo "Can not run git. Exiting..."
exit
fi

if ! command_exists gradle  ; then
    echo "Can not run gradle. Exiting..."
    exit
fi

echo "Creating clara working directory ..."
mkdir clara-work
cd clara-work

echo "Downloading and building xMsg package ..."
git clone https://github.com/JeffersonLab/xmsg-java.git
cd xmsg-java
gradle install

cd ..
echo "Downloading and building clara-java package ..."
git clone https://github.com/JeffersonLab/clara-java.git
cd clara-java
gradle install
gradle deploy

cd ..
echo "Downloading and building clasrec-io package ..."
git clone https://github.com/JeffersonLab/clasrec-io.git
cd clasrec-io
gradle deploy

cd ..
echo "Downloading and building clasrec-orchestrators package ..."
git clone https://github.com/JeffersonLab/clasrec-orchestrators.git
cd clasrec-orchestrators
gradle deploy

cd ..
echo "Downloading coat-java package ..."
case $OS in
  'Linux')
  wget https://userweb.jlab.org/~gavalian/software/coatjava/coatjava-3.0.tar.gz
    ;;
#  'WindowsNT')
#    OS='Windows'
#    ;;
  'Darwin')
 curl "https://userweb.jlab.org/~gavalian/software/coatjava/coatjava-3.0.tar.gz" -o coatjava-3.0.tar.gz
    ;;
  *) ;;
esac
 rm -rf coatjava
 tar xvzf coatjava-3.0.tar.gz
cd coat-java
cp lib/clas/* $CLARA_HOME/plugins/clas12/lib/.
cp lib/plugins/* $CLARA_HOME/plugins/clas12/services/.
cp -r etc $CLARA_HOME/plugins/clas12/.
rm -rf $CLARA_HOME/plugins/clas12/etc/services

mkdir $CLARA_HOME/data
mkdir $CLARA_HOME/data/in
mkdir $CLARA_HOME/data/out

hash -r
cp ../clasrec-io/data/gemcOut_header.evio $CLARA_HOME/data/in/

echo done