#!/usr/bin/env bash
# author Vardan Gyurjyan
# date 10.28.16

if ! [ -n "$CLARA_HOME" ]; then
    echo "CLARA_HOME is not defined. Exiting..."
    exit
fi

PLUGIN=coatjava-3a.0.1
while :
do
    case "$1" in
      -u | --update)
	  rm -rf $CLARA_HOME
	  shift 2
	  ;;
      -p | --plugin)
	  PLUGIN="$2"
	  shift 2
	  ;;

     *)  # No more options
	  break
	  ;;
    esac
done

command_exists () {
    type "$1" &> /dev/null ;
}

OS="`uname`"
case $OS in
  'Linux')

  if ! command_exists wget ; then
  echo "Can not run wget. Exiting..."
  exit
  fi

    wget https://userweb.jlab.org/~gurjyan/clara-cre/clara-cre.tar.gz
    wget https://userweb.jlab.org/~gavalian/software/coatjava/"$PLUGIN".tar.gz


    MACHINE_TYPE=`uname -m`
    if [ ${MACHINE_TYPE} == 'x86_64' ]; then
      wget https://userweb.jlab.org/~gurjyan/clara-cre/linux-64.tar.gz
    else
      wget https://userweb.jlab.org/~gurjyan/clara-cre/linux-i586.tar.gz
    fi
    ;;
#  'WindowsNT')
#    OS='Windows'
#    ;;
  'Darwin')

    if ! command_exists curl ; then
    echo "Can not run curl. Exiting..."
    exit
    fi

 curl "https://userweb.jlab.org/~gurjyan/clara-cre/clara-cre.tar.gz" -o clara-cre.tar.gz
 curl "https://userweb.jlab.org/~gavalian/software/coatjava/"$PLUGIN".tar.gz" -o "$PLUGIN".tar.gz

 curl "https://userweb.jlab.org/~gurjyan/clara-cre/macosx-64.tar.gz" -o macosx-64.tar.gz
    ;;
  *) ;;
esac

    tar xvzf clara-cre.tar.gz
    rm -f clara-cre.tar.gz
    cd clara-cre

    mkdir jre
    cd jre
    mv ../../*.tar.* .
    mv "$PLUGIN".tar.gz ../../.



echo "Installing jre ..."
tar xvzf *.tar.*
cd ../plugins
mkdir clas12/lib
mkdir clas12/services

cd ../..

echo `pwd`

tar xvzf "$PLUGIN".tar.gz

cp -r etc $CLARA_HOME/plugins/clas12/.
cp -r bin $CLARA_HOME/plugins/clas12/.
cp -r scripts $CLARA_HOME/plugins/clas12/.
cp -r lib $CLARA_HOME/plugins/clas12/.
rm -f $CLARA_HOME/plugins/clas12/bin/clara-rec
cp $CLARA_HOME/plugins/clas12/etc/services/reconstruction.yaml $CLARA_HOME/plugins/clas12/config/services.yaml
rm -rf $CLARA_HOME/plugins/clas12/etc/services

cd ..
rm -rf coatjava
rm "$PLUGIN".tar.gz

echo done
