#!/usr/bin/env bash

TEST_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

##############################################################################
# Launch cloud orchestrator
##############################################################################
if [ -n "$CLARA_HOME" ]; then
    export CLASSPATH="$CLARA_HOME/lib/*:$CLAS12DIR/lib/clas/*:$CLAS12DIR/lib/services/*"
    else
    echo "CLARA_HOME is not defined. Exiting..."
    exit
fi

if [ -n "${JAVA_OPTS}" ]; then
    jvm_options=("${JAVA_OPTS}")
else
    jvm_options=(-Xms1024m -Xmx2048m -XX:+UseNUMA -XX:+UseBiasedLocking)
fi

if [ -n "${JAVA_HOME}" ]; then
    java_bin="${JAVA_HOME}/bin/java"
else
    java_bin=java
fi


MAIN=org.jlab.clas.std.orchestrators.CloudOrchestrator
echo =====================================
echo "$LOG_FILE-co.log"
echo =====================================


"${java_bin}" -cp $CLASSPATH $MAIN "$@" 2>&1 | tee "$LOG_FILE-co.log"

# Cleanup after we done
#remove-dpe

exit ${PIPESTATUS[0]}
