#!/bin/sh

# author gurjyan
# date 2.7.15

if [ -n "$CLARA_HOME" ]; then
    export CLASSPATH="$CLARA_HOME/lib/*:$CLARA_HOME/services/*"
fi

if [ "$1" = "-h" ] || [ "$1" = "-help" ]; then
    echo ""
    echo "Starts CLARA dpe (java binding)"
    echo "-------------------------------- "
    echo "synopsis: j_dpe"
    echo ""
else

java -XX:+UseNUMA -XX:+UseBiasedLocking org.jlab.clara.sys.Dpe "$@"
fi
