#!/bin/sh

# author gurjyan
# date 2.9.15

if [ -n "$CLARA_HOME" ]; then
    export CLASSPATH="$CLARA_HOME/lib/*:$CLARA_HOME/services/*"
fi

if [ "$1" = "-h" ] || [ "$1" = "-help" ]; then
    echo ""
    echo "Starts the example of an interactive orchestrator(java binding)"
    echo "-------------------------------- "
    echo "synopsis: j_orchestrator"
    echo ""
else
java -XX:+UseNUMA -XX:+UseBiasedLocking org.jlab.clara.examples.orchestrators.OrInteractive $1 $2
fi
