#!/usr/bin/env bash
# author gurjyan
# date 2.7.15

if [ -n "$CLARA_HOME" ]; then
    export CLASSPATH="$CLARA_HOME/lib/*:$CLAS12DIR/lib/*:$CLAS12DIR/services/*"
    else
    echo "CLARA_HOME is not defined. Exiting..."
    exit
fi

java -Xms1024m -Xmx2048m -XX:+UseNUMA -XX:+UseBiasedLocking org.jlab.clara.sys.Dpe "$@"