#!/usr/bin/env bash

echo $1

a=`ps -ef | grep "session $1" | grep -v grep | awk '{print $2}'`
echo $a

for f in $a;
do
kill -9 $f
done

b=`ps -ef | grep "s $1" | grep -v grep | awk '{print $2}'`
echo $b

for ff in $b;
do
kill -9 $ff
done
