#!/usr/bin/env bash
# author Vardan Gyurjyan
# date 10.21.16

if ! [ -n "$CLARA_HOME" ]; then
    echo "CLARA_HOME is not defined. Exiting..."
    exit
fi

function display_help {

echo 'Usage: run-clara [option <operand>]'
echo
echo '  [-h | --help]'
echo '        Usage instructions'
echo
echo '  [-j | --java_home <java_home>]'
echo '        JDK/JRE installation directory. (default: %JAVA_HOME)'
echo
echo '  [-c | --clara_home <clara_home>]'
echo '        CLARA installation directory. (default: %CLARA_HOME)'
echo
echo '  [-p | --plugin <plugin>]'
echo '        Plugin installation directory. (default: %CLARA_HOME/plugins/clas12)'
echo
echo '  [-s | --session <session>]'
echo '        The data processing session. (default: $USER)'
echo
echo '  [-m | --mode <mode>]'
echo '        The data processing mode. (default: local. Accepts local2 and farm operands)'
echo
echo '  [-i | --input_dir <inputDir>]'
echo '        The input directory where the files to be processed are located.'
echo '        (default: $CLARA_HOME/../data/in)'
echo
echo '  [-o | --output_dir <outputDir>]'
echo '        The output directory where processed files will be saved.'
echo '        (default: $CLARA_HOME/../data/out)'
echo
echo '  [-n | --nodes <maxNodes>]'
echo '        The maximum number of processing nodes to be used. Farm mode only. (default: 1)'
echo
echo '  [-t | --threads <maxThreads>]'
echo '        The maximum number of processing threads to be used per node.'
echo '        (default: 36 for farm mode and local-node processor count otherwise))'
}

# Default parameter settings
# CLARA_HOME
CL_HOME=$CLARA_HOME

# Input data directory
IN_DIR="$CLARA_HOME/data/in"

# JAVA_HOME

OS="`uname`"
case $OS in
  'Linux')
if $(uname -a | grep 'x86_64'); then
  J_HOME=$CLARA_HOME/jre/linux-64/jre1.8.0_112
else
  J_HOME=$CLARA_HOME/jre/linux-i586/jre1.8.0_112
fi
    ;;
  'WindowsNT')
    OS='Windows'
    ;;
  'Darwin')
  J_HOME=$CLARA_HOME/jre/macosx-64/jre1.8.0_112.jre/Contents/Home
    ;;
  *) ;;
esac


# Running mode
MODE=local

# Number of nodes in case of farm deployment
NODE_NUM=1

# Output directory
OUT_DIR="$CLARA_HOME/data/out"

# User service plugin
PLUGIN="$CLARA_HOME/plugins/clas12"

# Data processing session
SESSION=$USER

# Number of parallel threads
THREAD_NUM=`getconf _NPROCESSORS_ONLN`

while :
do
    case "$1" in
      -c | --clara-home)
	  CL_HOME="$2"
	  shift 2
	  ;;
      -h | --help)
	  display_help  # function call
	  exit 0
	  ;;
      -i | --input-dir)
	  IN_DIR="$2"
	  shift 2
	  ;;
      -j | --java-home)
	  J_HOME="$2"
	  shift 2
	  ;;
      -m | --mode)
      {
      if [ "$2" == "farm" ] || [ "$2" == "local_2" ]; then
	      MODE="$2"
	  fi
	  }
	  shift 2
	  ;;
      -n | --nodes)
	  NODE_NUM="$2"
	  shift 2
	  ;;
      -o | --output-dir)
	  OUT_DIR="$2"
	  shift 2
	  ;;
      -p | --plugin)
	  PLUGIN="$2"
	  shift 2
	  ;;
      -s | --session)
	  SESSION="$2"
	  shift 2
	  ;;
      -t | --threads)
	  THREAD_NUM="$2"
	  shift 2
	  ;;
     *)  # No more options
	  break
	  ;;
    esac
done

export JAVA_HOME="$J_HOME"
export CLARA_HOME="$CL_HOME"
export CLAS12DIR="$PLUGIN"
export CCDB_DATABASE="etc/data/database/clas12database.sqlite"
export PATH=$PATH:$JAVA_HOME/bin:$CLARA_HOME/bin
export CLASSPATH="$CLARA_HOME/lib/*:$CLAS12DIR/lib/*:$CLAS12DIR/services/*"

SERVICE_YAML="$CLAS12DIR/config/services.yaml"
FILE_LIST="$CLAS12DIR/config/files.list"

if [ "$MODE" == "farm" ]; then
J_HOME=group/da/Java/jdk/1.8/x64/jdk1.8.0_102/
export JAVA_HOME="$J_HOME"
# ----------------- Farm deployment ----------------------
echo ' Note: Data input/output directories must be visible by JLAB farm nodes.'

# For farm nodes we set thread count to be 36 * 2
THREAD_NUM=36
# Build auger commands
rcCmd="COMMAND: run-clara -c $CLARA_HOME -i $IN_DIR -j $JAVA_HOME -m local_2 -o $OUT_DIR -p $CLAS12DIR -s $SESSION -t $THREAD_NUM"
rdpCmd="COMMAND: clara-2dpe  $SESSION $CLARA_HOME $CLAS12DIR"

# Create orchestrator job submission script
{
echo 'PROJECT: clas12'
echo 'JOBNAME: rec_$USER'
echo 'MEMORY: 30 GB'
echo 'TRACK: debug'
echo 'OS: centos65'
echo 'CPU: 48'
echo 'DISK_SPACE: 3 GB'

echo $rcCmd

} > $CLAS12DIR/config/clara_p.jsub
sleep 3

# Submit auger job request
jsub $CLAS12DIR/config/clara_p.jsub

# Create dpe job submission script
{
echo 'PROJECT: clas12'
echo 'JOBNAME: rec_$USER'
echo 'MEMORY: 30 GB'
echo 'TRACK: debug'
echo 'OS: centos65'
echo 'CPU: 48'
echo 'DISK_SPACE: 3 GB'

echo $rdpCmd

} > $CLAS12DIR/config/clara_d.jsub

for ((i = 1; i < $NODE_NUM; i++)); do
jsub $CLAS12DIR/config/clara_d.jsub
done

# ----------------- Local deployment ----------------------
else
# Starting DPEs
################# Starting DPE ############
UPPER=8000
PORT=7000
dpe_port=0
while  [ $dpe_port == 0 ]
do
dpe_port=0
exec 6<>/dev/tcp/127.0.0.1/$PORT || dpe_port=1
if [ $dpe_port == 0 ]; then
let "PORT=PORT+10"
fi
done
echo "$PORT"


if ! [ -z ${2+x} ]; then CLARA_HOME=$2; fi
if ! [ -z ${3+x} ]; then CLAS12DIR=$3; fi
if [ -z ${4+x} ]; then FE_HOST="localhost" ; else FE_HOST=$4; fi

echo $FE_HOST

export CLARA_HOME
export CLAS12DIR
export CCDB_DATABASE="etc/data/database/clas12database.sqlite"
export CLASSPATH="$CLARA_HOME/lib/*:$CLAS12DIR/lib/*:$CLAS12DIR/services/*"


LOG_FILE=$CLARA_HOME/log/$HOSTNAME

echo "-------- Running Conditions ---------------"
echo " Start time         = "$(date)
echo " Clara distribution = $CLARA_HOME"
echo " Plugin directory   = $CLAS12DIR"
echo " Log file           = Clara distribution/log/$HOSTNAME-jfe.log"
echo " Note               = Running as local Front-End"
echo "------------------------------------------"
echo
j_dpe --port $PORT --host $FE_HOST --session $SESSION 2>&1 | tee "$LOG_FILE-jfe.log" &

#j_dpe --port $PORT --host $FE_HOST --session $SESSION & export dpepid=$!

IP=$(host `hostname` | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")

################# Starting DPE ############

sleep 3

# We start second DPE if mode is set to farm
#if [ "$MODE" == "local_2" ]; then
#clara-dpe for multi-fe case
#clara-2dpe $SESSION &
#THREAD_NUM=36
#sleep 3
#fi

j="_java"
FENAME=$IP%$PORT$j

# Starting cloud orchestrator
j_cloud -f $FENAME -s $SESSION -F -i $IN_DIR -o $OUT_DIR -p $THREAD_NUM -t $THREAD_NUM $SERVICE_YAML $FILE_LIST

remove-dpe

fi



