#!/usr/bin/env bash
# author Vardan Gyurjyan
# date 11.03.16

unset CCDB_DATABASE

function display_help {
echo
echo 'Usage: run-clara [option <operand>]'
echo
echo '  [-h | --help]'
echo '        Usage instructions'
echo
echo '  [-j | --java_home <java_home>]'
echo '        JDK/JRE installation directory. (default: $JAVA_HOME)'
echo
echo '  [-c | --clara_home <clara_home>]'
echo '        CLARA installation directory. (default: $CLARA_HOME)'
echo
echo '  [-p | --plugin <plugin>]'
echo '        Plugin installation directory. (default: $CLARA_HOME/plugins/clas12)'
echo
echo '  [-s | --session <session>]'
echo '        The data processing session. (default: $USER)'
echo
echo '  [-m | --mode <mode>]'
echo '        The data processing mode. Accepts values = local, sqlite and farm (default: local)'
echo
echo '  [-i | --input_dir <inputDir>]'
echo '        The input directory where the files to be processed are located.'
echo '        (default: $CLARA_HOME/data/in)'
echo
echo '  [-o | --output_dir <outputDir>]'
echo '        The output directory where processed files will be saved.'
echo '        (default: $CLARA_HOME/data/out)'
echo
#echo '  [-n | --nodes <maxNodes>]'
#echo '        The maximum number of processing nodes to be used. Farm mode only. (default: 1)'
echo
echo '  [-t | --threads <maxThreads>]'
echo '        The maximum number of processing threads to be used per node. In case value = auto t=local-node processor count.'
echo '        (default: 36 for farm mode and 2 for the local mode))'
echo
echo '  [-f | --file-list <fileList>]'
echo '        Full path to the file containing the names of data-files to be processed. Note: actual files are located in the inputDir.'
echo '        (default: $CLARA_HOME/plugins/clas12/config/files.list)'
echo
echo '  [-y | --yaml <yamlComposition>]'
echo '        Full path to the file describing application service composition.'
echo '        (default: $CLARA_HOME/plugins/clas12/config/services.yaml)'

}

# Default parameter settings
CL_HOME="undefined"
IN_DIR="undefined"
J_HOME="undefined"
MODE="undefined"
NODE_NUM="undefined"
OUT_DIR="undefined"
PLUGIN="undefined"
SESSION="undefined"
THREAD_NUM="undefined"
SERVICE_YAML="undefined"
FILE_LIST="undefined"

while :
do
    case "$1" in
      -c | --clara-home)
	  CL_HOME="$2"
	  export CLARA_HOME="$CL_HOME"
	  shift 2
	  ;;
      -f | --files-list)
	  FILE_LIST="$2"
	  shift 2
	  ;;
      -h | --help)
	  display_help  # function call
	  exit 0
	  ;;
      -i | --input-dir)
	  IN_DIR="$2"
	  shift 2
	  ;;
      -j | --java-home)
	  J_HOME="$2"
	  shift 2
	  ;;
      -m | --mode)
      {
      if [ "$2" == "farm" ] || [ "$2" == "sqlite" ] ; then
	      MODE="$2"
	  fi
	  }
	  shift 2
	  ;;
#      -n | --nodes)
#	  NODE_NUM="$2"
#	  shift 2
#	  ;;
      -o | --output-dir)
	  OUT_DIR="$2"
	  shift 2
	  ;;
      -p | --plugin)
	  PLUGIN="$2"
	  shift 2
	  ;;
      -s | --session)
	  SESSION="$2"
	  shift 2
	  ;;
      -t | --threads)
	  THREAD_NUM="$2"

	  if [ "$THREAD_NUM" == "auto" ] ; then
	  THREAD_NUM=`getconf _NPROCESSORS_ONLN`
	  fi

	  shift 2
	  ;;
      -y | --yaml)
	  SERVICE_YAML="$2"
	  shift 2
	  ;;

     *)  # No more options
	  break
	  ;;
    esac
done


# CLARA_HOME
if [ "$CL_HOME" == "undefined" ]; then

if ! [ -n "$CLARA_HOME" ]; then
    echo "CLARA_HOME is not defined. Exiting..."
    exit
fi

CL_HOME=$CLARA_HOME

fi

# Input data directory
if [ "$IN_DIR" == "undefined" ]; then
IN_DIR="$CLARA_HOME/data/in"
fi

# JAVA_HOME
if [ "$J_HOME" == "undefined" ]; then

OS="`uname`"
case $OS in
  'Linux')
IP=$(host `hostname` | grep -oE "\b([0-9]{1,3}\.){3}[0-9]{1,3}\b")
  if [ -z "$IP" ]; then
  IP=127.0.0.1
  fi

    MACHINE_TYPE=`uname -m`
    if [ ${MACHINE_TYPE} == 'x86_64' ]; then

  J_HOME=$CLARA_HOME/jre/linux-64/jre1.8.0_112
else
  J_HOME=$CLARA_HOME/jre/linux-i586/jre1.8.0_112
fi
    ;;
  'WindowsNT')
    OS='Windows'
    ;;
  'Darwin')

  IP=$(ipconfig getifaddr en0)
  if [ -z "$IP" ]; then
  IP=$(ipconfig getifaddr en1)
  fi

if [ -z "$IP" ]; then
 IP=127.0.0.1
fi

  J_HOME=$CLARA_HOME/jre/macosx-64/jre1.8.0_112.jre/Contents/Home
    ;;
  *) ;;
esac
fi

# Running mode
if [ "$MODE" == "undefined" ]; then
MODE=local
fi

# Number of nodes in case of farm deployment
if [ "$NODE_NUM" == "undefined" ]; then
NODE_NUM=1
fi

# Output directory
if [ "$OUT_DIR" == "undefined" ]; then
OUT_DIR="$CLARA_HOME/data/out"
fi

# User service plugin
if [ "$PLUGIN" == "undefined" ]; then
PLUGIN="$CLARA_HOME/plugins/clas12"
fi

# Data processing session
if [ "$SESSION" == "undefined" ]; then
SESSION="$USER"
fi

# Number of parallel threads
if [ "$THREAD_NUM" == "undefined" ]; then
if [ "$MODE" = "farm" ]; then
THREAD_NUM=72
else
THREAD_NUM=2
fi
fi


export JAVA_HOME="$J_HOME"
export CLARA_HOME="$CL_HOME"
export CLAS12DIR="$PLUGIN"
#export CCDB_DATABASE="etc/data/database/clas12database.sqlite"
export PATH=$PATH:$JAVA_HOME/bin:$CLARA_HOME/bin
export CLASSPATH="$CLARA_HOME/lib/*:$CLAS12DIR/lib/clas/*:$CLAS12DIR/lib/services/*"

# Composition yaml file
if [ "$SERVICE_YAML" == "undefined" ]; then
SERVICE_YAML="$CLAS12DIR/config/services.yaml"
fi

# List of files to be processed
if [ "$FILE_LIST" == "undefined" ]; then
FILE_LIST="$CLAS12DIR/config/files.list"
fi

if [ "$MODE" == "farm" ]; then
#J_HOME=/group/da/Java/jdk/1.8/x64/jdk1.8.0_102/
#export JAVA_HOME="$J_HOME"
# ----------------- Farm deployment ----------------------
echo ' Note: CLARA distribution and data input/output directories must be visible to JLAB farm nodes.'

# Build auger commands
#rcCmd="COMMAND: setenv CLARA_HOME "$CL_HOME"; "$CLARA_HOME"/bin/run-clara -c "$CLARA_HOME" -i "$IN_DIR" -j "$JAVA_HOME" -m local_2 -o "$OUT_DIR" -p "$CLAS12DIR" -s "$SESSION" -t "$THREAD_NUM" -y "$SERVICE_YAML" -f "$FILE_LIST""


rcCmd="COMMAND: setenv CLARA_HOME "$CL_HOME"; $CLARA_HOME/bin/run-clara -i "$IN_DIR" -o "$OUT_DIR" -s "$SESSION" -t "$THREAD_NUM" -y "$SERVICE_YAML" -f "$FILE_LIST""
rdpCmd="COMMAND: setenv CLARA_HOME="$CL_HOME"; "$CLARA_HOME"/bin/clara-dpe  "$SESSION" "$CLARA_HOME" "$CLAS12DIR""

# Create orchestrator job submission script
{
echo "PROJECT: clas12"
echo "JOBNAME: rec_$USER"
echo "MEMORY: 70 GB"
echo "TRACK: debug"
echo "OS: centos7"
echo "CPU: 72"
echo "DISK_SPACE: 3 GB"
echo "TIME: 1440"

echo $rcCmd

} > $CLAS12DIR/config/clara_p.jsub
sleep 3

# Submit auger job request
jsub $CLAS12DIR/config/clara_p.jsub

# Create dpe job submission script
{
echo "PROJECT: clas12"
echo "JOBNAME: rec_$USER"
echo "MEMORY: 70 GB"
echo "TRACK: debug"
echo "OS: centos7"
echo "CPU: 72"
echo "DISK_SPACE: 3 GB"
echo "TIME: 1440"

echo $rdpCmd

} > $CLAS12DIR/config/clara_d.jsub

for ((i = 1; i < $NODE_NUM; i++)); do
jsub $CLAS12DIR/config/clara_d.jsub
done

# ----------------- Local deployment ----------------------
else


# We start second DPE if mode is set to farm
if [ "$MODE" == "sqlite" ]; then
export CCDB_DATABASE="etc/data/database/clas12database.sqlite"
fi

# reset dangling DPEs
$CLARA_HOME/bin/remove-dpe $SESSION

# Starting DPEs
################# Starting DPE ############
UPPER=8000
PORT=7000
dpe_port=0
while  [ $dpe_port == 0 ]
do
dpe_port=0
exec 6<>/dev/tcp/127.0.0.1/$PORT || dpe_port=1
if [ $dpe_port == 0 ]; then
let "PORT=PORT+10"
fi
done
echo "$PORT"


if ! [ -z ${2+x} ]; then CLARA_HOME=$2; fi
if ! [ -z ${3+x} ]; then CLAS12DIR=$3; fi
if [ -z ${4+x} ]; then FE_HOST="localhost" ; else FE_HOST=$4; fi

echo $FE_HOST

export CLARA_HOME
export CLAS12DIR
export CLASSPATH="$CLARA_HOME/lib/*:$CLAS12DIR/lib/*:$CLAS12DIR/services/*"


LOG_FILE=$CLARA_HOME/log/$HOSTNAME

echo "-------- Running Conditions ---------------"
echo " Start time         = "$(date)
echo " Clara distribution = $CLARA_HOME"
echo " Plugin directory   = $CLAS12DIR"
echo " Log file           = Clara distribution/log/$HOSTNAME-jfe.log"
echo " Note               = Running as local Front-End"
echo " Threads request    = $THREAD_NUM"
echo "------------------------------------------"
echo


$CLARA_HOME/bin/j_dpe --port $PORT --host $FE_HOST --session $SESSION --max-sockets 5120 --report 5 --max-cores $THREAD_NUM 2>&1 | tee "$LOG_FILE-jfe.log" &

#$CLARA_HOME/bin/j_dpe --port $PORT --host $FE_HOST --session $SESSION & export dpepid=$!

################# Starting DPE ############

sleep 20

j="_java"
FENAME=$IP%$PORT$j

# Starting cloud orchestrator
$CLARA_HOME/bin/j_cloud -f $FENAME -s $SESSION -F -i $IN_DIR -o $OUT_DIR -p $THREAD_NUM -t $THREAD_NUM $SERVICE_YAML $FILE_LIST

$CLARA_HOME/bin/remove-dpe $SESSION


fi



