#!/usr/bin/env bash
# author Vardan Gyurjyan
# date 10.28.16

command_exists () {
    type "$1" &> /dev/null ;
}

if ! [ -n "$CLARA_HOME" ]; then
    echo "CLARA_HOME is not defined. Exiting..."
    exit
fi

if ! command_exists git ; then
echo "Can not run git. Exiting..."
exit
fi


cd $CLARA_HOME/../clara-work

echo "Updating and building xMsg package ..."
cd xmsg-java
git pull
./gradlew install

cd ..
echo "Updating and building clara-java package ..."
cd clara-java
git pull
./gradlew install
./gradlew deploy

hash -r
echo done