#!/bin/sh

# Copyright (c) 2017.  Jefferson Lab (JLab). All rights reserved. Permission
# to use, copy, modify, and distribute  this software and its documentation for
# educational, research, and not-for-profit purposes, without fee and without a
# signed licensing agreement.
#
# IN NO EVENT SHALL JLAB BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, SPECIAL
# INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, ARISING
# OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF JLAB HAS
# BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# JLAB SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
# THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
# PURPOSE. THE CLARA SOFTWARE AND ACCOMPANYING DOCUMENTATION, IF ANY,
# PROVIDED HEREUNDER IS PROVIDED "AS IS". JLAB HAS NO OBLIGATION TO PROVIDE
# MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
#
# This software was developed under the United States Government license.
# For more information contact author at gurjyan@jlab.org
# Department of Experimental Nuclear Physics, Jefferson Lab.

java_dist=
case "$(uname)" in
    "Linux")
        if [ "$(uname -m)" = "x86_64" ]; then
            java_dist=$CLARA_HOME/jre/linux-64/jre
        else
            java_dist=$CLARA_HOME/jre/linux-i586/jre
        fi
        ;;

    "Darwin")
        java_dist=$CLARA_HOME/jre/macosx-64/jre/Contents/Home
        ;;

    *)  ;;
esac
if [ -n "$java_dist" ] && [ -d "$java_dist" ]; then
    export JAVA_HOME="$java_dist"
fi

if [ -n "$JAVA_HOME" ]; then
    java_bin="$JAVA_HOME/bin/java"
else
    java_bin=java
fi

exec "$java_bin" "$@"
