package claraol.impl;

import claraol.*;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultState <br>
 * @version generated on Sat Jan 30 17:43:59 EST 2016 by gurjyan
 */
public class DefaultState extends WrappedIndividualImpl implements State {

    public DefaultState(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasSeverity
     */
     
    public Collection<? extends String> getHasSeverity() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSEVERITY, String.class);
    }

    public boolean hasHasSeverity() {
		return !getHasSeverity().isEmpty();
    }

    public void addHasSeverity(String newHasSeverity) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSEVERITY, newHasSeverity);
    }

    public void removeHasSeverity(String oldHasSeverity) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSEVERITY, oldHasSeverity);
    }


    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasSeverityID
     */
     
    public Collection<? extends Integer> getHasSeverityID() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSEVERITYID, Integer.class);
    }

    public boolean hasHasSeverityID() {
		return !getHasSeverityID().isEmpty();
    }

    public void addHasSeverityID(Integer newHasSeverityID) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSEVERITYID, newHasSeverityID);
    }

    public void removeHasSeverityID(Integer oldHasSeverityID) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSEVERITYID, oldHasSeverityID);
    }


    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasStateName
     */
     
    public Collection<? extends String> getHasStateName() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSTATENAME, String.class);
    }

    public boolean hasHasStateName() {
		return !getHasStateName().isEmpty();
    }

    public void addHasStateName(String newHasStateName) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSTATENAME, newHasStateName);
    }

    public void removeHasStateName(String oldHasStateName) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_HASSTATENAME, oldHasStateName);
    }


}
