package org.jlab.clara.claraol.impl;


import java.util.Collection;

import org.jlab.clara.claraol.ServiceConfig;
import org.jlab.clara.claraol.Vocabulary;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultServiceConfig <br>
 * @version generated on Sat Jan 30 17:43:59 EST 2016 by gurjyan
 */
public class DefaultServiceConfig extends WrappedIndividualImpl implements ServiceConfig {

    public DefaultServiceConfig(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#broadcastDone
     */
     
    public Collection<? extends Boolean> getBroadcastDone() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_BROADCASTDONE, Boolean.class);
    }

    public boolean hasBroadcastDone() {
		return !getBroadcastDone().isEmpty();
    }

    public void addBroadcastDone(Boolean newBroadcastDone) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_BROADCASTDONE, newBroadcastDone);
    }

    public void removeBroadcastDone(Boolean oldBroadcastDone) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_BROADCASTDONE, oldBroadcastDone);
    }


    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#broadcastError
     */
     
    public Collection<? extends Boolean> getBroadcastError() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_BROADCASTERROR, Boolean.class);
    }

    public boolean hasBroadcastError() {
		return !getBroadcastError().isEmpty();
    }

    public void addBroadcastError(Boolean newBroadcastError) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_BROADCASTERROR, newBroadcastError);
    }

    public void removeBroadcastError(Boolean oldBroadcastError) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_BROADCASTERROR, oldBroadcastError);
    }


    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#broadcastWarning
     */
     
    public Collection<? extends Boolean> getBroadcastWarning() {
		return getDelegate().getPropertyValues(getOwlIndividual(), Vocabulary.DATA_PROPERTY_BROADCASTWARNING, Boolean.class);
    }

    public boolean hasBroadcastWarning() {
		return !getBroadcastWarning().isEmpty();
    }

    public void addBroadcastWarning(Boolean newBroadcastWarning) {
	    getDelegate().addPropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_BROADCASTWARNING, newBroadcastWarning);
    }

    public void removeBroadcastWarning(Boolean oldBroadcastWarning) {
		getDelegate().removePropertyValue(getOwlIndividual(), Vocabulary.DATA_PROPERTY_BROADCASTWARNING, oldBroadcastWarning);
    }


}
