#!/usr/bin/env bash
# author Vardan Gyurjyan
# date 1.13.17


rm -rf $CLARA_HOME/plugins/clas12/bin
rm -rf $CLARA_HOME/plugins/clas12/etc
rm -rf $CLARA_HOME/plugins/clas12/log
rm -rf $CLARA_HOME/plugins/clas12/scripts
rm $CLARA_HOME/data/out/*

rm -rf $CLARA_HOME/jre
cd $CLARA_HOME/..

tar cvf clara-cre.tar clara-cre
gzip clara-cre.tar

