#!/bin/sh

export CLARA_COMMAND_WRAPPER=./scripts/lib/cmd-wrapper
export CLARA_COMMAND_LOGGER=./scripts/lib/cmd-logger
export CLARA_TEMPLATES_DIR=./scripts/lib/templates
exec ./scripts/exec-class org.jlab.clara.std.cli.ClaraShell "$@"
