#!/usr/bin/env bash

if [ $# -gt 0 ]; then
    printf -v var "'%s', " "$@"
    var=${var%??}
    gradle --console plain listenReports -PlistRepArgs="[$var]"
else
    gradle --console plain listenReports
fi
