package claraol;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Action <br>
 * @version generated on Sat Jan 30 17:43:59 EST 2016 by gurjyan
 */

public interface Action extends WrappedIndividual {

    /* ***************************************************
     * Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#sendsData
     */
     
    /**
     * Gets all property values for the sendsData property.<p>
     * 
     * @returns a collection of values for the sendsData property.
     */
    Collection<? extends DataSource> getSendsData();

    /**
     * Checks if the class has a sendsData property value.<p>
     * 
     * @return true if there is a sendsData property value.
     */
    boolean hasSendsData();

    /**
     * Adds a sendsData property value.<p>
     * 
     * @param newSendsData the sendsData property value to be added
     */
    void addSendsData(DataSource newSendsData);

    /**
     * Removes a sendsData property value.<p>
     * 
     * @param oldSendsData the sendsData property value to be removed.
     */
    void removeSendsData(DataSource oldSendsData);


    /* ***************************************************
     * Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#sendsTo
     */
     
    /**
     * Gets all property values for the sendsTo property.<p>
     * 
     * @returns a collection of values for the sendsTo property.
     */
    Collection<? extends Service> getSendsTo();

    /**
     * Checks if the class has a sendsTo property value.<p>
     * 
     * @return true if there is a sendsTo property value.
     */
    boolean hasSendsTo();

    /**
     * Adds a sendsTo property value.<p>
     * 
     * @param newSendsTo the sendsTo property value to be added
     */
    void addSendsTo(Service newSendsTo);

    /**
     * Removes a sendsTo property value.<p>
     * 
     * @param oldSendsTo the sendsTo property value to be removed.
     */
    void removeSendsTo(Service oldSendsTo);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
