package org.jlab.clara.claraol;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: EngineConfig <br>
 * @version generated on Sat Jan 30 17:43:59 EST 2016 by gurjyan
 */

public interface EngineConfig extends WrappedIndividual {

    /* ***************************************************
     * Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasInputData
     */
     
    /**
     * Gets all property values for the hasInputData property.<p>
     * 
     * @return a collection of values for the hasInputData property.
     */
    Collection<? extends DataSource> getHasInputData();

    /**
     * Checks if the class has a hasInputData property value.<p>
     * 
     * @return true if there is a hasInputData property value.
     */
    boolean hasHasInputData();

    /**
     * Adds a hasInputData property value.<p>
     * 
     * @param newHasInputData the hasInputData property value to be added
     */
    void addHasInputData(DataSource newHasInputData);

    /**
     * Removes a hasInputData property value.<p>
     * 
     * @param oldHasInputData the hasInputData property value to be removed.
     */
    void removeHasInputData(DataSource oldHasInputData);


    /* ***************************************************
     * Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasOutputData
     */
     
    /**
     * Gets all property values for the hasOutputData property.<p>
     * 
     * @return a collection of values for the hasOutputData property.
     */
    Collection<? extends DataSource> getHasOutputData();

    /**
     * Checks if the class has a hasOutputData property value.<p>
     * 
     * @return true if there is a hasOutputData property value.
     */
    boolean hasHasOutputData();

    /**
     * Adds a hasOutputData property value.<p>
     * 
     * @param newHasOutputData the hasOutputData property value to be added
     */
    void addHasOutputData(DataSource newHasOutputData);

    /**
     * Removes a hasOutputData property value.<p>
     * 
     * @param oldHasOutputData the hasOutputData property value to be removed.
     */
    void removeHasOutputData(DataSource oldHasOutputData);


    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
