package claraol;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: Identity <br>
 * @version generated on Sat Jan 30 17:43:59 EST 2016 by gurjyan
 */

public interface Identity extends WrappedIndividual {

    /* ***************************************************
     * Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#author
     */
     
    /**
     * Gets all property values for the author property.<p>
     * 
     * @returns a collection of values for the author property.
     */
    Collection<? extends String> getAuthor();

    /**
     * Checks if the class has a author property value.<p>
     * 
     * @return true if there is a author property value.
     */
    boolean hasAuthor();

    /**
     * Adds a author property value.<p>
     * 
     * @param newAuthor the author property value to be added
     */
    void addAuthor(String newAuthor);

    /**
     * Removes a author property value.<p>
     * 
     * @param oldAuthor the author property value to be removed.
     */
    void removeAuthor(String oldAuthor);



    /* ***************************************************
     * Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#description
     */
     
    /**
     * Gets all property values for the description property.<p>
     * 
     * @returns a collection of values for the description property.
     */
    Collection<? extends String> getDescription();

    /**
     * Checks if the class has a description property value.<p>
     * 
     * @return true if there is a description property value.
     */
    boolean hasDescription();

    /**
     * Adds a description property value.<p>
     * 
     * @param newDescription the description property value to be added
     */
    void addDescription(String newDescription);

    /**
     * Removes a description property value.<p>
     * 
     * @param oldDescription the description property value to be removed.
     */
    void removeDescription(String oldDescription);



    /* ***************************************************
     * Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#name
     */
     
    /**
     * Gets all property values for the name property.<p>
     * 
     * @returns a collection of values for the name property.
     */
    Collection<? extends String> getName();

    /**
     * Checks if the class has a name property value.<p>
     * 
     * @return true if there is a name property value.
     */
    boolean hasName();

    /**
     * Adds a name property value.<p>
     * 
     * @param newName the name property value to be added
     */
    void addName(String newName);

    /**
     * Removes a name property value.<p>
     * 
     * @param oldName the name property value to be removed.
     */
    void removeName(String oldName);



    /* ***************************************************
     * Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#version
     */
     
    /**
     * Gets all property values for the version property.<p>
     * 
     * @returns a collection of values for the version property.
     */
    Collection<? extends String> getVersion();

    /**
     * Checks if the class has a version property value.<p>
     * 
     * @return true if there is a version property value.
     */
    boolean hasVersion();

    /**
     * Adds a version property value.<p>
     * 
     * @param newVersion the version property value to be added
     */
    void addVersion(String newVersion);

    /**
     * Removes a version property value.<p>
     * 
     * @param oldVersion the version property value to be removed.
     */
    void removeVersion(String oldVersion);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
