package org.jlab.clara.claraol;

import java.util.Collection;

import org.protege.owl.codegeneration.WrappedIndividual;

import org.semanticweb.owlapi.model.OWLNamedIndividual;
import org.semanticweb.owlapi.model.OWLOntology;

/**
 * 
 * <p>
 * Generated by Protege (http://protege.stanford.edu). <br>
 * Source Class: State <br>
 * @version generated on Sat Jan 30 17:43:59 EST 2016 by gurjyan
 */

public interface State extends WrappedIndividual {

    /* ***************************************************
     * Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasSeverity
     */
     
    /**
     * Gets all property values for the hasSeverity property.<p>
     * 
     * @return a collection of values for the hasSeverity property.
     */
    Collection<? extends String> getHasSeverity();

    /**
     * Checks if the class has a hasSeverity property value.<p>
     * 
     * @return true if there is a hasSeverity property value.
     */
    boolean hasHasSeverity();

    /**
     * Adds a hasSeverity property value.<p>
     * 
     * @param newHasSeverity the hasSeverity property value to be added
     */
    void addHasSeverity(String newHasSeverity);

    /**
     * Removes a hasSeverity property value.<p>
     * 
     * @param oldHasSeverity the hasSeverity property value to be removed.
     */
    void removeHasSeverity(String oldHasSeverity);



    /* ***************************************************
     * Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasSeverityID
     */
     
    /**
     * Gets all property values for the hasSeverityID property.<p>
     * 
     * @return a collection of values for the hasSeverityID property.
     */
    Collection<? extends Integer> getHasSeverityID();

    /**
     * Checks if the class has a hasSeverityID property value.<p>
     * 
     * @return true if there is a hasSeverityID property value.
     */
    boolean hasHasSeverityID();

    /**
     * Adds a hasSeverityID property value.<p>
     * 
     * @param newHasSeverityID the hasSeverityID property value to be added
     */
    void addHasSeverityID(Integer newHasSeverityID);

    /**
     * Removes a hasSeverityID property value.<p>
     * 
     * @param oldHasSeverityID the hasSeverityID property value to be removed.
     */
    void removeHasSeverityID(Integer oldHasSeverityID);



    /* ***************************************************
     * Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasStateName
     */
     
    /**
     * Gets all property values for the hasStateName property.<p>
     * 
     * @return a collection of values for the hasStateName property.
     */
    Collection<? extends String> getHasStateName();

    /**
     * Checks if the class has a hasStateName property value.<p>
     * 
     * @return true if there is a hasStateName property value.
     */
    boolean hasHasStateName();

    /**
     * Adds a hasStateName property value.<p>
     * 
     * @param newHasStateName the hasStateName property value to be added
     */
    void addHasStateName(String newHasStateName);

    /**
     * Removes a hasStateName property value.<p>
     * 
     * @param oldHasStateName the hasStateName property value to be removed.
     */
    void removeHasStateName(String oldHasStateName);



    /* ***************************************************
     * Common interfaces
     */

    OWLNamedIndividual getOwlIndividual();

    OWLOntology getOwlOntology();

    void delete();

}
