/*
 *   Copyright (c) 2016.  Jefferson Lab (JLab). All rights reserved. Permission
 *   to use, copy, modify, and distribute  this software and its documentation for
 *   educational, research, and not-for-profit purposes, without fee and without a
 *   signed licensing agreement.
 *
 *   IN NO EVENT SHALL JLAB BE LIABLE TO ANY PARTY FOR DIRECT, INDIRECT, SPECIAL
 *   INCIDENTAL, OR CONSEQUENTIAL DAMAGES, INCLUDING LOST PROFITS, ARISING
 *   OUT OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF JLAB HAS
 *   BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 *   JLAB SPECIFICALLY DISCLAIMS ANY WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
 *   THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
 *   PURPOSE. THE CLARA SOFTWARE AND ACCOMPANYING DOCUMENTATION, IF ANY,
 *   PROVIDED HEREUNDER IS PROVIDED "AS IS". JLAB HAS NO OBLIGATION TO PROVIDE
 *   MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS.
 *
 *   This software was developed under the United States Government license.
 *   For more information contact author at gurjyan@jlab.org
 *   Department of Experimental Nuclear Physics, Jefferson Lab.
 */

package org.jlab.clara.claraol;

import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.*;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Sat Jan 30 17:43:59 EST 2016 by gurjyan
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://claraweb.jlab.org/ontology/2015/11/ClaraOL#Action
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ACTION.<p>
     * 
     */
    public static final OWLClass CLASS_ACTION = factory.getOWLClass(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#Action"));

    /* ***************************************************
     * Class http://claraweb.jlab.org/ontology/2015/11/ClaraOL#Application
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class APPLICATION.<p>
     * 
     */
    public static final OWLClass CLASS_APPLICATION = factory.getOWLClass(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#Application"));

    /* ***************************************************
     * Class http://claraweb.jlab.org/ontology/2015/11/ClaraOL#Condition
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONDITION.<p>
     * 
     */
    public static final OWLClass CLASS_CONDITION = factory.getOWLClass(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#Condition"));

    /* ***************************************************
     * Class http://claraweb.jlab.org/ontology/2015/11/ClaraOL#DataSet
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DATASET.<p>
     * 
     */
    public static final OWLClass CLASS_DATASET = factory.getOWLClass(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#DataSet"));

    /* ***************************************************
     * Class http://claraweb.jlab.org/ontology/2015/11/ClaraOL#DataSource
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DATASOURCE.<p>
     * 
     */
    public static final OWLClass CLASS_DATASOURCE = factory.getOWLClass(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#DataSource"));

    /* ***************************************************
     * Class http://claraweb.jlab.org/ontology/2015/11/ClaraOL#Engine
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ENGINE.<p>
     * 
     */
    public static final OWLClass CLASS_ENGINE = factory.getOWLClass(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#Engine"));

    /* ***************************************************
     * Class http://claraweb.jlab.org/ontology/2015/11/ClaraOL#EngineConfig
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ENGINECONFIG.<p>
     * 
     */
    public static final OWLClass CLASS_ENGINECONFIG = factory.getOWLClass(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#EngineConfig"));

    /* ***************************************************
     * Class http://claraweb.jlab.org/ontology/2015/11/ClaraOL#Identity
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class IDENTITY.<p>
     * 
     */
    public static final OWLClass CLASS_IDENTITY = factory.getOWLClass(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#Identity"));

    /* ***************************************************
     * Class http://claraweb.jlab.org/ontology/2015/11/ClaraOL#Orchestrator
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ORCHESTRATOR.<p>
     * 
     */
    public static final OWLClass CLASS_ORCHESTRATOR = factory.getOWLClass(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#Orchestrator"));

    /* ***************************************************
     * Class http://claraweb.jlab.org/ontology/2015/11/ClaraOL#Service
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SERVICE.<p>
     * 
     */
    public static final OWLClass CLASS_SERVICE = factory.getOWLClass(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#Service"));

    /* ***************************************************
     * Class http://claraweb.jlab.org/ontology/2015/11/ClaraOL#ServiceConfig
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SERVICECONFIG.<p>
     * 
     */
    public static final OWLClass CLASS_SERVICECONFIG = factory.getOWLClass(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#ServiceConfig"));

    /* ***************************************************
     * Class http://claraweb.jlab.org/ontology/2015/11/ClaraOL#State
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class STATE.<p>
     * 
     */
    public static final OWLClass CLASS_STATE = factory.getOWLClass(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#State"));

    /* ***************************************************
     * Object Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#actsOnError
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ACTSONERROR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ACTSONERROR = factory.getOWLObjectProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#actsOnError"));

    /* ***************************************************
     * Object Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#actsOnWarning
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ACTSONWARNING.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ACTSONWARNING = factory.getOWLObjectProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#actsOnWarning"));

    /* ***************************************************
     * Object Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#executionState
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property EXECUTIONSTATE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_EXECUTIONSTATE = factory.getOWLObjectProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#executionState"));

    /* ***************************************************
     * Object Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasCondition
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCONDITION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCONDITION = factory.getOWLObjectProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasCondition"));

    /* ***************************************************
     * Object Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasConfig
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCONFIG.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCONFIG = factory.getOWLObjectProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasConfig"));

    /* ***************************************************
     * Object Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasEngine
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASENGINE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASENGINE = factory.getOWLObjectProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasEngine"));

    /* ***************************************************
     * Object Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasEventSink
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASEVENTSINK.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASEVENTSINK = factory.getOWLObjectProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasEventSink"));

    /* ***************************************************
     * Object Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasEventSource
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASEVENTSOURCE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASEVENTSOURCE = factory.getOWLObjectProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasEventSource"));

    /* ***************************************************
     * Object Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasIdentity
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASIDENTITY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASIDENTITY = factory.getOWLObjectProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasIdentity"));

    /* ***************************************************
     * Object Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasInputData
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASINPUTDATA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASINPUTDATA = factory.getOWLObjectProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasInputData"));

    /* ***************************************************
     * Object Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasInputSource
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASINPUTSOURCE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASINPUTSOURCE = factory.getOWLObjectProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasInputSource"));

    /* ***************************************************
     * Object Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasLink
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASLINK.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASLINK = factory.getOWLObjectProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasLink"));

    /* ***************************************************
     * Object Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasOutputData
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASOUTPUTDATA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASOUTPUTDATA = factory.getOWLObjectProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasOutputData"));

    /* ***************************************************
     * Object Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasOutputSource
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASOUTPUTSOURCE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASOUTPUTSOURCE = factory.getOWLObjectProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasOutputSource"));

    /* ***************************************************
     * Object Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasService
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSERVICE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSERVICE = factory.getOWLObjectProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasService"));

    /* ***************************************************
     * Object Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasSkipAction
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSKIPACTION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSKIPACTION = factory.getOWLObjectProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasSkipAction"));

    /* ***************************************************
     * Object Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasStartAction
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSTARTACTION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSTARTACTION = factory.getOWLObjectProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasStartAction"));

    /* ***************************************************
     * Object Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasState
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSTATE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSTATE = factory.getOWLObjectProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasState"));

    /* ***************************************************
     * Object Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasStopAction
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASSTOPACTION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASSTOPACTION = factory.getOWLObjectProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasStopAction"));

    /* ***************************************************
     * Object Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#ifFalseSend
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IFFALSESEND.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IFFALSESEND = factory.getOWLObjectProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#ifFalseSend"));

    /* ***************************************************
     * Object Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#ifTrueSend
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property IFTRUESEND.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_IFTRUESEND = factory.getOWLObjectProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#ifTrueSend"));

    /* ***************************************************
     * Object Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#needsConfiguation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property NEEDSCONFIGUATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_NEEDSCONFIGUATION = factory.getOWLObjectProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#needsConfiguation"));

    /* ***************************************************
     * Object Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#processes
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property PROCESSES.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_PROCESSES = factory.getOWLObjectProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#processes"));

    /* ***************************************************
     * Object Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#receivedState
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property RECEIVEDSTATE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_RECEIVEDSTATE = factory.getOWLObjectProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#receivedState"));

    /* ***************************************************
     * Object Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#runs
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property RUNS.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_RUNS = factory.getOWLObjectProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#runs"));

    /* ***************************************************
     * Object Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#sendsData
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SENDSDATA.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SENDSDATA = factory.getOWLObjectProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#sendsData"));

    /* ***************************************************
     * Object Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#sendsTo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property SENDSTO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_SENDSTO = factory.getOWLObjectProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#sendsTo"));

    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#author
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property AUTHOR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_AUTHOR = factory.getOWLDataProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#author"));

    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#broadcastDone
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property BROADCASTDONE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_BROADCASTDONE = factory.getOWLDataProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#broadcastDone"));

    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#broadcastError
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property BROADCASTERROR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_BROADCASTERROR = factory.getOWLDataProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#broadcastError"));

    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#broadcastWarning
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property BROADCASTWARNING.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_BROADCASTWARNING = factory.getOWLDataProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#broadcastWarning"));

    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#description
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property DESCRIPTION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_DESCRIPTION = factory.getOWLDataProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#description"));

    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasComposition
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCOMPOSITION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCOMPOSITION = factory.getOWLDataProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasComposition"));

    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasContainer
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASCONTAINER.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASCONTAINER = factory.getOWLDataProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasContainer"));

    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasDpe
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASDPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASDPE = factory.getOWLDataProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasDpe"));

    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasLibrary
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLIBRARY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLIBRARY = factory.getOWLDataProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasLibrary"));

    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasLibraryPath
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASLIBRARYPATH.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASLIBRARYPATH = factory.getOWLDataProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasLibraryPath"));

    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasPoolSize
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASPOOLSIZE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASPOOLSIZE = factory.getOWLDataProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasPoolSize"));

    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasSeverity
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSEVERITY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSEVERITY = factory.getOWLDataProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasSeverity"));

    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasSeverityID
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSEVERITYID.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSEVERITYID = factory.getOWLDataProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasSeverityID"));

    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasStateName
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASSTATENAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASSTATENAME = factory.getOWLDataProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasStateName"));

    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasType
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASTYPE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASTYPE = factory.getOWLDataProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasType"));

    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasValue
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASVALUE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASVALUE = factory.getOWLDataProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#hasValue"));

    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#isDirectory
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ISDIRECTORY.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ISDIRECTORY = factory.getOWLDataProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#isDirectory"));

    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#isFile
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property ISFILE.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_ISFILE = factory.getOWLDataProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#isFile"));

    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#logicalRelationship
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property LOGICALRELATIONSHIP.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_LOGICALRELATIONSHIP = factory.getOWLDataProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#logicalRelationship"));

    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#monitorsError
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property MONITORSERROR.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_MONITORSERROR = factory.getOWLDataProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#monitorsError"));

    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#monitorsInfo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property MONITORSINFO.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_MONITORSINFO = factory.getOWLDataProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#monitorsInfo"));

    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#monitorsWarning
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property MONITORSWARNING.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_MONITORSWARNING = factory.getOWLDataProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#monitorsWarning"));

    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#name
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property NAME.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_NAME = factory.getOWLDataProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#name"));

    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#outputFilePrefix
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property OUTPUTFILEPREFIX.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_OUTPUTFILEPREFIX = factory.getOWLDataProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#outputFilePrefix"));

    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#outputFileSuffix
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property OUTPUTFILESUFFIX.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_OUTPUTFILESUFFIX = factory.getOWLDataProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#outputFileSuffix"));

    /* ***************************************************
     * Data Property http://claraweb.jlab.org/ontology/2015/11/ClaraOL#version
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property VERSION.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_VERSION = factory.getOWLDataProperty(IRI.create("http://claraweb.jlab.org/ontology/2015/11/ClaraOL#version"));


}
